# Generated by Django 5.1.3 on 2024-12-20 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classsession_course_department_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
